### ISSUE TITLE
RustBridge Event Checklist

### ISSUE THREAD

**Issue by broesamle** [rust-community/rustbridge#62]
This Template Checklist is a result of our experiences at the first RustBridge (cf. #60) 
It can be copied for each particular event.

- [ ] Invitation (incl. time, location, what to bring/prepare)
- [ ] Install instructions that match the planned workshops (cf. #53) for Win/MAC/Linux
- [ ] Room
- [ ] Internet connection (enough bandwidth for the expected number of people)
- [ ] Electricity (multiplier cables)
- [ ] Tea, Coffee, Drinks, Snacks
- [ ] Signage/Posters to guide to location, bathrooms etc. (scotch tape)
- [ ] Projector
- [ ] Starting web address as long as we do not have landing page (#1) 
- [ ] Slides/Document for the intro #44  !!!
- [ ] Printout of install cheat sheets (to be extracted from installfest docs) (Helpful but not prio 1 since most of the applicants have experiences already)
